package py.edu.ucsa.voto.entity;
// Generated 06/07/2017 07:49:28 PM by Hibernate Tools 4.3.1


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

/**
 * UcsawsVigenciaHorarioXPais generated by hbm2java
 */
@Entity
@Table(name = "ucsaws_vigencia_horario_x_pais")
public class UcsawsVigenciaHorarioXPais implements java.io.Serializable {

  @Id
  @Column(name = "id_vigencia", nullable = false)
  @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
  @SequenceGenerator(name = "generator", sequenceName = "ucsaws_vigencia_seq", allocationSize = 1)
  private Integer idVigencia;
  
  @ManyToOne(fetch = FetchType.EAGER)
  @Cascade(value = { CascadeType.LOCK })
  @JoinColumn(name = "id_pais", referencedColumnName = "id_pais")
  private UcsawsPais idPais;
  
  @ManyToOne(fetch = FetchType.EAGER)
  @Cascade(value = { CascadeType.LOCK })
  @JoinColumn(name = "id_evento", referencedColumnName = "id_evento")
  private UcsawsEvento idEvento;
  
  
  @Column(name = "fch_vigencia_desde", nullable = false)
  @Temporal(TemporalType.TIMESTAMP)
  private Date fchVigenciaDesde;
  
  @Column(name = "fch_vigencia_hasta", nullable = false)
  @Temporal(TemporalType.TIMESTAMP)
  private Date fchVigenciaHasta;


  @Column(name = "fch_ins", nullable = false)
  @Temporal(TemporalType.TIMESTAMP)
  private Date fchIns;
  
  @Column(name = "fch_upd", nullable = true)
  @Temporal(TemporalType.TIMESTAMP)
  private Date fchUpd;
  
  @Column(name = "usuario_ins", nullable = false)
  private String usuarioIns;
  
  @Column(name = "usuario_upd", nullable = true)
  private String usuarioUpd;

  public UcsawsVigenciaHorarioXPais() {}


  public UcsawsVigenciaHorarioXPais(Integer idVigencia, UcsawsPais idPais, UcsawsEvento idEvento, String usuarioIns) {
    this.idVigencia = idVigencia;
    this.idPais = idPais;
    this.idEvento = idEvento;
    this.usuarioIns = usuarioIns;
  }

  public UcsawsVigenciaHorarioXPais(Integer idVigencia, UcsawsPais idPais, Date fchVigenciaDesde,
      Date fchVigenciaHasta, Date fchIns, Date fchUpd, UcsawsEvento idEvento, String usuarioIns,
      String usuarioUpd) {
    this.idVigencia = idVigencia;
    this.idPais = idPais;
    this.fchVigenciaDesde = fchVigenciaDesde;
    this.fchVigenciaHasta = fchVigenciaHasta;
    this.fchIns = fchIns;
    this.fchUpd = fchUpd;
    this.idEvento = idEvento;
    this.usuarioIns = usuarioIns;
    this.usuarioUpd = usuarioUpd;
  }

  public Integer getIdVigencia() {
    return this.idVigencia;
  }

  public void setIdVigencia(Integer idVigencia) {
    this.idVigencia = idVigencia;
  }

  public UcsawsPais getIdPais() {
    return this.idPais;
  }

  public void setIdPais(UcsawsPais idPais) {
    this.idPais = idPais;
  }

  public Date getFchVigenciaDesde() {
    return this.fchVigenciaDesde;
  }

  public void setFchVigenciaDesde(Date fchVigenciaDesde) {
    this.fchVigenciaDesde = fchVigenciaDesde;
  }

  public Date getFchVigenciaHasta() {
    return this.fchVigenciaHasta;
  }

  public void setFchVigenciaHasta(Date fchVigenciaHasta) {
    this.fchVigenciaHasta = fchVigenciaHasta;
  }

  public Date getFchIns() {
    return this.fchIns;
  }

  public void setFchIns(Date fchIns) {
    this.fchIns = fchIns;
  }

  public Date getFchUpd() {
    return this.fchUpd;
  }

  public void setFchUpd(Date fchUpd) {
    this.fchUpd = fchUpd;
  }

  public UcsawsEvento getIdEvento() {
    return this.idEvento;
  }

  public void setIdEvento(UcsawsEvento idEvento) {
    this.idEvento = idEvento;
  }

  public String getUsuarioIns() {
    return this.usuarioIns;
  }

  public void setUsuarioIns(String usuarioIns) {
    this.usuarioIns = usuarioIns;
  }

  public String getUsuarioUpd() {
    return this.usuarioUpd;
  }

  public void setUsuarioUpd(String usuarioUpd) {
    this.usuarioUpd = usuarioUpd;
  }



}
