package py.edu.ucsa.voto.entity;

// Generated 25/04/2017 03:26:32 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

/**
 * UcsawsPais generated by hbm2java
 */
@Entity
@Table(name = "ucsaws_pais")
public class UcsawsPais implements java.io.Serializable {

	@Id
	@Column(name = "id_pais", nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@SequenceGenerator(name = "generator", sequenceName = "ucsaws_pais_seq", allocationSize = 1)
	private Integer idPais;

	@Column(name = "fch_ins", nullable = false)
	@Temporal(TemporalType.TIMESTAMP)
	private Date fchIns;

	@Column(name = "fch_upd", nullable = true)
	@Temporal(TemporalType.TIMESTAMP)
	private Date fchUpd;

	@Column(name = "usuario_ins", nullable = false)
	private String usuarioIns;

	@Column(name = "usuario_upd", nullable = true)
	private String usuarioUpd;

	@Column(name = "nombre", nullable = true)
	private String nombre;

	@Column(name = "codigo", nullable = true)
	private String codigo;

	@ManyToOne(fetch = FetchType.EAGER)
	@Cascade(value = { CascadeType.LOCK })
	@JoinColumn(name = "id_evento", referencedColumnName = "id_evento")
	private UcsawsEvento idEvento;



	public UcsawsPais() {
	}

	public UcsawsPais(Integer idPais, Date fchIns, String usuarioIns,
			String nombre, UcsawsEvento idEvento) {
		this.idPais = idPais;
		this.fchIns = fchIns;
		this.usuarioIns = usuarioIns;
		this.nombre = nombre;
		this.idEvento = idEvento;
	}

	public UcsawsPais(Integer idPais, Date fchIns, Date fchUpd, String usuarioIns,
			String usuarioUpd, String nombre, String codigo,
			UcsawsEvento idEvento, UcsawsPais ucsawsPersonasForIdPaisActual,
			
			UcsawsPais ucsawsPersonasForIdPaisOrigen) {
		this.idPais = idPais;
		this.fchIns = fchIns;
		this.fchUpd = fchUpd;
		this.usuarioIns = usuarioIns;
		this.usuarioUpd = usuarioUpd;
		this.nombre = nombre;
		this.codigo = codigo;
		this.idEvento = idEvento;

		

	}

	public Integer getIdPais() {
		return this.idPais;
	}

	public void setIdPais(Integer idPais) {
		this.idPais = idPais;
	}

	public Date getFchIns() {
		return this.fchIns;
	}

	public void setFchIns(Date fchIns) {
		this.fchIns = fchIns;
	}

	public Date getFchUpd() {
		return this.fchUpd;
	}

	public void setFchUpd(Date fchUpd) {
		this.fchUpd = fchUpd;
	}

	public String getUsuarioIns() {
		return this.usuarioIns;
	}

	public void setUsuarioIns(String usuarioIns) {
		this.usuarioIns = usuarioIns;
	}

	public String getUsuarioUpd() {
		return this.usuarioUpd;
	}

	public void setUsuarioUpd(String usuarioUpd) {
		this.usuarioUpd = usuarioUpd;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public UcsawsEvento getIdEvento() {
		return this.idEvento;
	}

	public void setIdEvento(UcsawsEvento idEvento) {
		this.idEvento = idEvento;
	}



	
}
