package py.edu.ucsa.voto.entity;
// Generated 22/04/2017 10:29:02 PM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

/**
 * UcsawsTipoEvento generated by hbm2java
 */
@Entity
@Table(name = "ucsaws_tipo_evento")
public class UcsawsTipoEvento  implements Serializable {

	public UcsawsTipoEvento(Integer idTipoEvento, String descripcion,
			Date fchIns, Date fchUpd, String usuarioIns, String usuarioUpd,
			Integer idEvento) {
		//super();
		this.idTipoEvento = idTipoEvento;
		this.descripcion = descripcion;
		this.fchIns = fchIns;
		this.fchUpd = fchUpd;
		this.usuarioIns = usuarioIns;
		this.usuarioUpd = usuarioUpd;
		this.idEvento = idEvento;
	}

	@Id
	@Column(name = "id_tipo_evento", nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@SequenceGenerator(name = "generator", sequenceName = "ucsaws_tipo_evento_seq", allocationSize = 1)
	private Integer idTipoEvento;
	
	@Column(name = "descripcion", nullable = false)
	private String descripcion;
	
	@Column(name = "fch_ins", nullable = false)
	@Temporal(TemporalType.TIMESTAMP)
	private Date fchIns;
	
	@Column(name = "fch_upd", nullable = true)
	@Temporal(TemporalType.TIMESTAMP)
	private Date fchUpd;
	
	@Column(name = "usuario_ins", nullable = false)
	private String usuarioIns;
	
	@Column(name = "usuario_upd", nullable = true)
	private String usuarioUpd;
	
	
	@Column(name = "id_evento", nullable = false)
	private Integer idEvento;

	public UcsawsTipoEvento() {
	}

	public Integer getIdTipoEvento() {
		return idTipoEvento;
	}

	public void setIdTipoEvento(Integer idTipoEvento) {
		this.idTipoEvento = idTipoEvento;
	}

	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Date getFchIns() {
		return fchIns;
	}

	public void setFchIns(Date fchIns) {
		this.fchIns = fchIns;
	}

	public Date getFchUpd() {
		return fchUpd;
	}

	public void setFchUpd(Date fchUpd) {
		this.fchUpd = fchUpd;
	}

	public String getUsuarioIns() {
		return usuarioIns;
	}

	public void setUsuarioIns(String usuarioIns) {
		this.usuarioIns = usuarioIns;
	}

	public String getUsuarioUpd() {
		return usuarioUpd;
	}

	public void setUsuarioUpd(String usuarioUpd) {
		this.usuarioUpd = usuarioUpd;
	}

	public Integer getIdEvento() {
		return idEvento;
	}

	public void setIdEvento(Integer idEvento) {
		this.idEvento = idEvento;
	}

	

}
