package py.edu.ucsa.voto.entity;
// Generated 25/04/2017 09:24:26 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

/**
 * UcsawsDepartamento generated by hbm2java
 */
@Entity
@Table(name = "ucsaws_departamento")
public class UcsawsDepartamento implements java.io.Serializable {

	@Id
	@Column(name = "id_departamento", nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@SequenceGenerator(name = "generator", sequenceName = "ucsaws_departamento_seq", allocationSize = 1)
	private Integer idDepartamento;
	
	@Column(name = "desc_departamento", nullable = false, length=1000)
	private String descDepartamento;
	
	@Column(name = "nro_departamento", nullable = false, length=1000)
	private String nroDepartamento;
	
	@Column(name = "fch_ins", nullable = false)
	@Temporal(TemporalType.TIMESTAMP)
	private Date fchIns;
	
	@Column(name = "fch_upd", nullable = true)
	@Temporal(TemporalType.TIMESTAMP)
	private Date fchUpd;
	
	@Column(name = "usuario_ins", nullable = false)
	private String usuarioIns;
	
	@Column(name = "usuario_upd", nullable = true)
	private String usuarioUpd;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@Cascade(value = { CascadeType.LOCK })
	@JoinColumn(name = "id_evento", referencedColumnName = "id_evento")
	private UcsawsEvento idEvento;


	public UcsawsDepartamento() {
	}

	public UcsawsDepartamento(Integer idDepartamento) {
		this.idDepartamento = idDepartamento;
	}

	public UcsawsDepartamento(Integer idDepartamento, String descDepartamento,
			String nroDepartamento, String usuarioIns, String usuarioUpd,
			Date fchIns, Date fchUpd, UcsawsEvento idEvento) {
		this.idDepartamento = idDepartamento;
		this.descDepartamento = descDepartamento;
		this.nroDepartamento = nroDepartamento;
		this.usuarioIns = usuarioIns;
		this.usuarioUpd = usuarioUpd;
		this.fchIns = fchIns;
		this.fchUpd = fchUpd;
		this.idEvento = idEvento;
		
	}

	public Integer getIdDepartamento() {
		return this.idDepartamento;
	}

	public void setIdDepartamento(Integer idDepartamento) {
		this.idDepartamento = idDepartamento;
	}

	public String getDescDepartamento() {
		return this.descDepartamento;
	}

	public void setDescDepartamento(String descDepartamento) {
		this.descDepartamento = descDepartamento;
	}

	public String getNroDepartamento() {
		return this.nroDepartamento;
	}

	public void setNroDepartamento(String nroDepartamento) {
		this.nroDepartamento = nroDepartamento;
	}

	public String getUsuarioIns() {
		return this.usuarioIns;
	}

	public void setUsuarioIns(String usuarioIns) {
		this.usuarioIns = usuarioIns;
	}

	public String getUsuarioUpd() {
		return this.usuarioUpd;
	}

	public void setUsuarioUpd(String usuarioUpd) {
		this.usuarioUpd = usuarioUpd;
	}

	public Date getFchIns() {
		return this.fchIns;
	}

	public void setFchIns(Date fchIns) {
		this.fchIns = fchIns;
	}

	public Date getFchUpd() {
		return this.fchUpd;
	}

	public void setFchUpd(Date fchUpd) {
		this.fchUpd = fchUpd;
	}

	public UcsawsEvento getIdEvento() {
		return this.idEvento;
	}

	public void setIdEvento(UcsawsEvento idEvento) {
		this.idEvento = idEvento;
	}

	

}
