package py.edu.ucsa.voto.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

/**
 * UcsawsNacionalidad generated by hbm2java
 */
@Entity
@Table(name = "ucsaws_nacionalidad")
public class UcsawsNacionalidad implements java.io.Serializable {

	
	@Id
	@Column(name = "id_nacionalidad", nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@SequenceGenerator(name = "generator", sequenceName = "ucsaws_nacionalidad_seq", allocationSize = 1)
	private Integer idNacionalidad;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@Cascade(value = { CascadeType.LOCK })
	@JoinColumn(name = "id_pais", referencedColumnName = "id_pais")
	private UcsawsPais ucsawsPais;
	
	@Column(name = "cod_nacionalidad", nullable = false)
	private String codNacionalidad;
	
	@Column(name = "desc_nacionalidad", nullable = false)
	private String descNacionalidad;
	
	
	@Column(name = "fch_ins", nullable = false)
	@Temporal(TemporalType.TIMESTAMP)
	private Date fchIns;
	
	@Column(name = "fch_upd", nullable = true)
	@Temporal(TemporalType.TIMESTAMP)
	private Date fchUpd;
	
	@Column(name = "usuario_ins", nullable = false)
	private String usuarioIns;
	
	@Column(name = "usuario_upd", nullable = true)
	private String usuarioUpd;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@Cascade(value = { CascadeType.LOCK })
	@JoinColumn(name = "id_evento", referencedColumnName = "id_evento")
	private UcsawsEvento idEvento;
	
	

	public UcsawsNacionalidad() {
	}

	public UcsawsNacionalidad(Integer idNacionalidad, UcsawsPais ucsawsPais) {
		this.idNacionalidad = idNacionalidad;
		this.ucsawsPais = ucsawsPais;
	}

	public UcsawsNacionalidad(Integer idNacionalidad, UcsawsPais ucsawsPais,
			String codNacionalidad, String descNacionalidad, String usuarioIns,
			String usuarioUpd, Date fchIns, Date fchUpd, UcsawsEvento idEvento,
			Set ucsawsPersonas) {
		this.idNacionalidad = idNacionalidad;
		this.ucsawsPais = ucsawsPais;
		this.codNacionalidad = codNacionalidad;
		this.descNacionalidad = descNacionalidad;
		this.usuarioIns = usuarioIns;
		this.usuarioUpd = usuarioUpd;
		this.fchIns = fchIns;
		this.fchUpd = fchUpd;
		this.idEvento = idEvento;
		
	}

	public Integer getIdNacionalidad() {
		return this.idNacionalidad;
	}

	public void setIdNacionalidad(Integer idNacionalidad) {
		this.idNacionalidad = idNacionalidad;
	}

	public UcsawsPais getUcsawsPais() {
		return this.ucsawsPais;
	}

	public void setUcsawsPais(UcsawsPais ucsawsPais) {
		this.ucsawsPais = ucsawsPais;
	}

	public String getCodNacionalidad() {
		return this.codNacionalidad;
	}

	public void setCodNacionalidad(String codNacionalidad) {
		this.codNacionalidad = codNacionalidad;
	}

	public String getDescNacionalidad() {
		return this.descNacionalidad;
	}

	public void setDescNacionalidad(String descNacionalidad) {
		this.descNacionalidad = descNacionalidad;
	}

	public String getUsuarioIns() {
		return this.usuarioIns;
	}

	public void setUsuarioIns(String usuarioIns) {
		this.usuarioIns = usuarioIns;
	}

	public String getUsuarioUpd() {
		return this.usuarioUpd;
	}

	public void setUsuarioUpd(String usuarioUpd) {
		this.usuarioUpd = usuarioUpd;
	}

	public Date getFchIns() {
		return this.fchIns;
	}

	public void setFchIns(Date fchIns) {
		this.fchIns = fchIns;
	}

	public Date getFchUpd() {
		return this.fchUpd;
	}

	public void setFchUpd(Date fchUpd) {
		this.fchUpd = fchUpd;
	}

	public UcsawsEvento getIdEvento() {
		return this.idEvento;
	}

	public void setIdEvento(UcsawsEvento idEvento) {
		this.idEvento = idEvento;
	}



}
