package py.edu.ucsa.voto.entity;
// default package
// Generated 25/04/2017 09:24:26 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

/**
 * UcsawsVotante generated by hbm2java
 */
@Entity
@Table(name = "ucsaws_votante")
public class UcsawsVotante implements java.io.Serializable {

	@Id
	@Column(name = "id_votante", nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@SequenceGenerator(name = "generator", sequenceName = "ucsaws_votante_seq", allocationSize = 1)
	private Integer idVotante;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@Cascade(value = { CascadeType.LOCK })
	@JoinColumn(name = "id_mesa", referencedColumnName = "id_mesa")
	private UcsawsMesa ucsawsMesa;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@Cascade(value = { CascadeType.LOCK })
	@JoinColumn(name = "id_persona", referencedColumnName = "id_persona")
	private UcsawsPersona idPersona;
	
	@Column(name = "sufrago", nullable = false)
	private Integer sufrago;

	@Column(name = "habilitado", nullable = false)
	private Integer habilitado;
	
	@Column(name = "fch_ins", nullable = false)
	@Temporal(TemporalType.TIMESTAMP)
	private Date fchIns;
	
	@Column(name = "fch_upd", nullable = true)
	@Temporal(TemporalType.TIMESTAMP)
	private Date fchUpd;
	
	@Column(name = "usuario_ins", nullable = false)
	private String usuarioIns;
	
	@Column(name = "usuario_upd", nullable = true)
	private String usuarioUpd;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@Cascade(value = { CascadeType.LOCK })
	@JoinColumn(name = "id_evento", referencedColumnName = "id_evento")
	private UcsawsEvento idEvento;

	public UcsawsVotante() {
	}

	public UcsawsVotante(Integer idVotante, UcsawsMesa ucsawsMesa, UcsawsPersona idPersona,
			Integer sufrago, Date fchIns, String usuarioIns, Integer habilitado,
			UcsawsEvento idEvento) {
		this.idVotante = idVotante;
		this.ucsawsMesa = ucsawsMesa;
		this.idPersona = idPersona;
		this.sufrago = sufrago;
		this.fchIns = fchIns;
		this.usuarioIns = usuarioIns;
		this.habilitado = habilitado;
		this.idEvento = idEvento;
	}

	public UcsawsVotante(Integer idVotante, UcsawsMesa ucsawsMesa, UcsawsPersona idPersona,
			Integer sufrago, Date fchIns, Date fchUpd, String usuarioIns,
			String usuarioUpd, Integer habilitado, UcsawsEvento idEvento) {
		this.idVotante = idVotante;
		this.ucsawsMesa = ucsawsMesa;
		this.idPersona = idPersona;
		this.sufrago = sufrago;
		this.fchIns = fchIns;
		this.fchUpd = fchUpd;
		this.usuarioIns = usuarioIns;
		this.usuarioUpd = usuarioUpd;
		this.habilitado = habilitado;
		this.idEvento = idEvento;
	}

	public Integer getIdVotante() {
		return this.idVotante;
	}

	public void setIdVotante(Integer idVotante) {
		this.idVotante = idVotante;
	}

	public UcsawsMesa getUcsawsMesa() {
		return this.ucsawsMesa;
	}

	public void setUcsawsMesa(UcsawsMesa ucsawsMesa) {
		this.ucsawsMesa = ucsawsMesa;
	}

	public UcsawsPersona getIdPersona() {
		return this.idPersona;
	}

	public void setIdPersona(UcsawsPersona idPersona) {
		this.idPersona = idPersona;
	}

	public Integer getSufrago() {
		return this.sufrago;
	}

	public void setSufrago(Integer sufrago) {
		this.sufrago = sufrago;
	}

	public Date getFchIns() {
		return this.fchIns;
	}

	public void setFchIns(Date fchIns) {
		this.fchIns = fchIns;
	}

	public Date getFchUpd() {
		return this.fchUpd;
	}

	public void setFchUpd(Date fchUpd) {
		this.fchUpd = fchUpd;
	}

	public String getUsuarioIns() {
		return this.usuarioIns;
	}

	public void setUsuarioIns(String usuarioIns) {
		this.usuarioIns = usuarioIns;
	}

	public String getUsuarioUpd() {
		return this.usuarioUpd;
	}

	public void setUsuarioUpd(String usuarioUpd) {
		this.usuarioUpd = usuarioUpd;
	}

	public Integer getHabilitado() {
		return this.habilitado;
	}

	public void setHabilitado(Integer habilitado) {
		this.habilitado = habilitado;
	}

	public UcsawsEvento getIdEvento() {
		return this.idEvento;
	}

	public void setIdEvento(UcsawsEvento idEvento) {
		this.idEvento = idEvento;
	}

}
