package py.edu.ucsa.voto.entity;

// default package
// Generated 30/05/2017 06:35:51 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

/**
 * UcsawsCandidatos generated by hbm2java
 */
@Entity
@Table(name = "ucsaws_candidatos")
public class UcsawsCandidatos implements java.io.Serializable {

    @Id
    @Column(name = "id_candidatos", nullable = false)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
    @SequenceGenerator(name = "generator", sequenceName = "ucsaws_candidatos_seq", allocationSize = 1)
    private Integer idCandidatos;

    @ManyToOne(fetch = FetchType.EAGER)
    @Cascade(value = { CascadeType.LOCK })
    @JoinColumn(name = "id_persona", referencedColumnName = "id_persona")
    private UcsawsPersona idPersona;
    
    @ManyToOne(fetch = FetchType.EAGER)
    @Cascade(value = { CascadeType.LOCK })
    @JoinColumn(name = "id_lista", referencedColumnName = "id_lista")
    private UcsawsListas idLista;

    @Column(name = "codigo", nullable = false, length=20)
    private String codigo;

    @Column(name = "descripcion", nullable = false, length=20)
    private String descripcion;

    @ManyToOne(fetch = FetchType.EAGER)
    @Cascade(value = { CascadeType.LOCK })
    @JoinColumn(name = "id_evento", referencedColumnName = "id_evento")
    private UcsawsEvento idEvento;

    @Column(name = "fch_ins", nullable = false)
    @Temporal(TemporalType.TIMESTAMP)
    private Date fchIns;

    @Column(name = "fch_upd", nullable = true)
    @Temporal(TemporalType.TIMESTAMP)
    private Date fchUpd;

    @Column(name = "usuario_ins", nullable = false)
    private String usuarioIns;

    @Column(name = "usuario_upd", nullable = true)
    private String usuarioUpd;

    public UcsawsCandidatos() {
    }

    public UcsawsCandidatos(Integer idCandidatos, UcsawsPersona idPersona, UcsawsListas idLista,
	    Date fchIns, String usuarioIns, UcsawsEvento idEvento) {
	this.idCandidatos = idCandidatos;
	this.idPersona = idPersona;
	this.idLista = idLista;
	this.fchIns = fchIns;
	this.usuarioIns = usuarioIns;
	this.idEvento = idEvento;
    }

    public UcsawsCandidatos(Integer idCandidatos, UcsawsPersona idPersona, UcsawsListas idLista,
	    Date fchIns, Date fchUpd, String usuarioIns, String usuarioUpd,
	    String codigo, UcsawsEvento idEvento, String descripcion) {
	this.idCandidatos = idCandidatos;
	this.idPersona = idPersona;
	this.idLista = idLista;
	this.fchIns = fchIns;
	this.fchUpd = fchUpd;
	this.usuarioIns = usuarioIns;
	this.usuarioUpd = usuarioUpd;
	this.codigo = codigo;
	this.idEvento = idEvento;
	this.descripcion = descripcion;
    }

    public Integer getIdCandidatos() {
	return this.idCandidatos;
    }

    public void setIdCandidatos(Integer idCandidatos) {
	this.idCandidatos = idCandidatos;
    }

    public Date getFchIns() {
	return this.fchIns;
    }

    public void setFchIns(Date fchIns) {
	this.fchIns = fchIns;
    }

    public Date getFchUpd() {
	return this.fchUpd;
    }

    public void setFchUpd(Date fchUpd) {
	this.fchUpd = fchUpd;
    }

    public String getUsuarioIns() {
	return this.usuarioIns;
    }

    public void setUsuarioIns(String usuarioIns) {
	this.usuarioIns = usuarioIns;
    }

    public String getUsuarioUpd() {
	return this.usuarioUpd;
    }

    public void setUsuarioUpd(String usuarioUpd) {
	this.usuarioUpd = usuarioUpd;
    }

    public String getCodigo() {
	return this.codigo;
    }

    public void setCodigo(String codigo) {
	this.codigo = codigo;
    }



    public String getDescripcion() {
	return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
	this.descripcion = descripcion;
    }

    public UcsawsPersona getIdPersona() {
        return idPersona;
    }

    public void setIdPersona(UcsawsPersona idPersona) {
        this.idPersona = idPersona;
    }

    public UcsawsListas getIdLista() {
        return idLista;
    }

    public void setIdLista(UcsawsListas idLista) {
        this.idLista = idLista;
    }

    public UcsawsEvento getIdEvento() {
        return idEvento;
    }

    public void setIdEvento(UcsawsEvento idEvento) {
        this.idEvento = idEvento;
    }
    
    

}
