package py.edu.ucsa.voto.entity;
// Generated 25/04/2017 03:26:32 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

/**
 * UcsawsUsers generated by hbm2java
 */
@Entity
@Table(name = "ucsaws_users")
public class UcsawsUsers implements java.io.Serializable {

	@Id
	@Column(name = "id_user", nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@SequenceGenerator(name = "generator", sequenceName = "ucsaws_users_seq", allocationSize = 1)
	private Integer idUser;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@Cascade(value = { CascadeType.LOCK })
	@JoinColumn(name = "id_persona", referencedColumnName = "id_persona")
	private UcsawsPersona ucsawsPersona;
	
	@Column(name = "fch_ins", nullable = false)
	@Temporal(TemporalType.TIMESTAMP)
	private Date fchIns;
	
	@Column(name = "fch_upd", nullable = true)
	@Temporal(TemporalType.TIMESTAMP)
	private Date fchUpd;
	
	@Column(name = "usuario_ins", nullable = false)
	private String usuarioIns;
	
	@Column(name = "usuario_upd", nullable = true)
	private String usuarioUpd;
	
	@Column(name = "pass", nullable = false)
	private String pass;
	
	@Column(name = "es_admin", nullable = false)
	private Boolean esAdmin;
	
	@Column(name = "usuario", nullable = false)
	private String usuario;
	
	@Column(name = "id_evento", nullable = false)
	private Integer idEvento;
	
	@Column(name = "id_rol", nullable = false)
	private Integer idRol;

	public UcsawsUsers() {
	}

	public UcsawsUsers(Integer idUser, UcsawsPersona ucsawsPersona, Date fchIns,
			String usuarioIns) {
		this.idUser = idUser;
		this.ucsawsPersona = ucsawsPersona;
		this.fchIns = fchIns;
		this.usuarioIns = usuarioIns;
	}

	public UcsawsUsers(Integer idUser, UcsawsPersona ucsawsPersona, Date fchIns,
			Date fchUpd, String usuarioIns, String usuarioUpd, String pass,
			Boolean esAdmin, String usuario, Integer idEvento, Integer idRol) {
		this.idUser = idUser;
		this.ucsawsPersona = ucsawsPersona;
		this.fchIns = fchIns;
		this.fchUpd = fchUpd;
		this.usuarioIns = usuarioIns;
		this.usuarioUpd = usuarioUpd;
		this.pass = pass;
		this.esAdmin = esAdmin;
		this.usuario = usuario;
		this.idEvento = idEvento;
		this.idRol = idRol;
	}

	public Integer getIdUser() {
		return this.idUser;
	}

	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}

	public UcsawsPersona getUcsawsPersona() {
		return this.ucsawsPersona;
	}

	public void setUcsawsPersona(UcsawsPersona ucsawsPersona) {
		this.ucsawsPersona = ucsawsPersona;
	}

	public Date getFchIns() {
		return this.fchIns;
	}

	public void setFchIns(Date fchIns) {
		this.fchIns = fchIns;
	}

	public Date getFchUpd() {
		return this.fchUpd;
	}

	public void setFchUpd(Date fchUpd) {
		this.fchUpd = fchUpd;
	}

	public String getUsuarioIns() {
		return this.usuarioIns;
	}

	public void setUsuarioIns(String usuarioIns) {
		this.usuarioIns = usuarioIns;
	}

	public String getUsuarioUpd() {
		return this.usuarioUpd;
	}

	public void setUsuarioUpd(String usuarioUpd) {
		this.usuarioUpd = usuarioUpd;
	}

	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

	public Boolean getEsAdmin() {
		return this.esAdmin;
	}

	public void setEsAdmin(Boolean esAdmin) {
		this.esAdmin = esAdmin;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public Integer getIdEvento() {
		return this.idEvento;
	}

	public void setIdEvento(Integer idEvento) {
		this.idEvento = idEvento;
	}

	public Integer getIdRol() {
		return this.idRol;
	}

	public void setIdRol(Integer idRol) {
		this.idRol = idRol;
	}

}
