package py.edu.ucsa.voto.entity;
// Generated 26/04/2017 09:41:37 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

/**
 * UcsawsListas generated by hbm2java
 */
@Entity
@Table(name = "ucsaws_listas")
public class UcsawsListas implements java.io.Serializable {

	@Id
	@Column(name = "id_lista", nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@SequenceGenerator(name = "generator", sequenceName = "ucsaws_listas_seq", allocationSize = 1)
	private Integer idLista;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@Cascade(value = { CascadeType.LOCK })
	@JoinColumn(name = "id_tipo_lista", referencedColumnName = "id_tipo_lista")
	private UcsawsTipoLista ucsawsTipoLista;
	
	@Column(name = "nombre_lista", nullable = false)
	private String nombreLista;
	
	@Column(name = "anho", nullable = false)
	private Integer anho;
	
	@Column(name = "fch_ins", nullable = false)
	@Temporal(TemporalType.TIMESTAMP)
	private Date fchIns;
	
	@Column(name = "fch_upd", nullable = true)
	@Temporal(TemporalType.TIMESTAMP)
	private Date fchUpd;
	
	@Column(name = "usuario_ins", nullable = true)
	private String usuarioIns;
	
	@Column(name = "usuario_upd", nullable = true)
	private String usuarioUpd;
	
	
	@Column(name = "nro_lista", nullable = true)
	private Integer nroLista;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@Cascade(value = { CascadeType.LOCK })
	@JoinColumn(name = "id_Evento", referencedColumnName = "id_Evento")
	private UcsawsEvento idEvento;
	

	public UcsawsListas() {
	}

	public UcsawsListas(Integer idLista, String nombreLista, Integer anho, Date fchIns,
			String usuarioIns, UcsawsEvento idEvento) {
		this.idLista = idLista;
		this.nombreLista = nombreLista;
		this.anho = anho;
		this.fchIns = fchIns;
		this.usuarioIns = usuarioIns;
		this.idEvento = idEvento;
	}

	public UcsawsListas(Integer idLista, UcsawsTipoLista ucsawsTipoLista,
			String nombreLista, Integer anho, Date fchIns, Date fchUpd,
			String usuarioIns, String usuarioUpd, Integer nroLista, UcsawsEvento idEvento) {
		this.idLista = idLista;
		this.ucsawsTipoLista = ucsawsTipoLista;
		this.nombreLista = nombreLista;
		this.anho = anho;
		this.fchIns = fchIns;
		this.fchUpd = fchUpd;
		this.usuarioIns = usuarioIns;
		this.usuarioUpd = usuarioUpd;
		this.nroLista = nroLista;
		this.idEvento = idEvento;
	}

	public Integer getIdLista() {
		return this.idLista;
	}

	public void setIdLista(Integer idLista) {
		this.idLista = idLista;
	}

	public UcsawsTipoLista getUcsawsTipoLista() {
		return this.ucsawsTipoLista;
	}

	public void setUcsawsTipoLista(UcsawsTipoLista ucsawsTipoLista) {
		this.ucsawsTipoLista = ucsawsTipoLista;
	}

	public String getNombreLista() {
		return this.nombreLista;
	}

	public void setNombreLista(String nombreLista) {
		this.nombreLista = nombreLista;
	}

	public Integer getAnho() {
		return this.anho;
	}

	public void setAnho(Integer anho) {
		this.anho = anho;
	}

	public Date getFchIns() {
		return this.fchIns;
	}

	public void setFchIns(Date fchIns) {
		this.fchIns = fchIns;
	}

	public Date getFchUpd() {
		return this.fchUpd;
	}

	public void setFchUpd(Date fchUpd) {
		this.fchUpd = fchUpd;
	}

	public String getUsuarioIns() {
		return this.usuarioIns;
	}

	public void setUsuarioIns(String usuarioIns) {
		this.usuarioIns = usuarioIns;
	}

	public String getUsuarioUpd() {
		return this.usuarioUpd;
	}

	public void setUsuarioUpd(String usuarioUpd) {
		this.usuarioUpd = usuarioUpd;
	}

	public Integer getNroLista() {
		return this.nroLista;
	}

	public void setNroLista(Integer nroLista) {
		this.nroLista = nroLista;
	}

	public UcsawsEvento getIdEvento() {
		return this.idEvento;
	}

	public void setIdEvento(UcsawsEvento idEvento) {
		this.idEvento = idEvento;
	}

}
