package py.edu.ucsa.voto.entity;
// default package
// Generated 26/04/2017 09:41:37 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

/**
 * UcsawsTipoLista generated by hbm2java
 */
@Entity
@Table(name = "ucsaws_tipo_lista")
public class UcsawsTipoLista implements java.io.Serializable {

	
	@Id
	@Column(name = "id_tipo_lista", nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@SequenceGenerator(name = "generator", sequenceName = "ucsaws_tipo_lista_seq", allocationSize = 1)
	private Integer idTipoLista;
	
	@Column(name = "descripcion", nullable = true)
	private String descripcion;

	@Column(name = "codigo", nullable = true)
	private String codigo;
	
	@Column(name = "fch_ins", nullable = false)
	@Temporal(TemporalType.TIMESTAMP)
	private Date fchIns;
	
	@Column(name = "fch_upd", nullable = true)
	@Temporal(TemporalType.TIMESTAMP)
	private Date fchUpd;
	
	@Column(name = "usuario_ins", nullable = true)
	private String usuarioIns;
	
	@Column(name = "usuario_upd", nullable = true)
	private String usuarioUpd;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@Cascade(value = { CascadeType.LOCK })
	@JoinColumn(name = "id_Evento", referencedColumnName = "id_Evento")
	private UcsawsEvento idEvento;
	

	public UcsawsTipoLista() {
	}

	public UcsawsTipoLista(Integer idTipoLista, String descripcion, Date fchIns,
			String usuarioIns, String codigo) {
		this.idTipoLista = idTipoLista;
		this.descripcion = descripcion;
		this.fchIns = fchIns;
		this.usuarioIns = usuarioIns;
		this.codigo = codigo;
	}

	public UcsawsTipoLista(Integer idTipoLista, String descripcion, Date fchIns,
			Date fchUpd, String usuarioIns, String usuarioUpd, String codigo,
			UcsawsEvento idEvento) {
		this.idTipoLista = idTipoLista;
		this.descripcion = descripcion;
		this.fchIns = fchIns;
		this.fchUpd = fchUpd;
		this.usuarioIns = usuarioIns;
		this.usuarioUpd = usuarioUpd;
		this.codigo = codigo;
		this.idEvento = idEvento;
		
	}

	public Integer getIdTipoLista() {
		return this.idTipoLista;
	}

	public void setIdTipoLista(Integer idTipoLista) {
		this.idTipoLista = idTipoLista;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Date getFchIns() {
		return this.fchIns;
	}

	public void setFchIns(Date fchIns) {
		this.fchIns = fchIns;
	}

	public Date getFchUpd() {
		return this.fchUpd;
	}

	public void setFchUpd(Date fchUpd) {
		this.fchUpd = fchUpd;
	}

	public String getUsuarioIns() {
		return this.usuarioIns;
	}

	public void setUsuarioIns(String usuarioIns) {
		this.usuarioIns = usuarioIns;
	}

	public String getUsuarioUpd() {
		return this.usuarioUpd;
	}

	public void setUsuarioUpd(String usuarioUpd) {
		this.usuarioUpd = usuarioUpd;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public UcsawsEvento getIdEvento() {
		return this.idEvento;
	}

	public void setIdEvento(UcsawsEvento idEvento) {
		this.idEvento = idEvento;
	}


}
