package py.edu.ucsa.voto.entity;
// default package
// Generated 25/04/2017 09:24:26 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

/**
 * UcsawsLocal generated by hbm2java
 */

@Entity
@Table(name = "ucsaws_local")
public class UcsawsLocal implements java.io.Serializable {

	
	@Id
	@Column(name = "id_local", nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@SequenceGenerator(name = "generator", sequenceName = "ucsaws_local_seq", allocationSize = 1)
	private int idLocal;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@Cascade(value = { CascadeType.LOCK })
	@JoinColumn(name = "id_zona", referencedColumnName = "id_zona")
	private UcsawsZona ucsawsZona;
	
	@Column(name = "desc_local", nullable = false, length=1000)
	private String descLocal;
	
	@Column(name = "nro_local", nullable = false, length=1000)
	private String nroLocal;
	
	@Column(name = "fch_ins", nullable = false)
	@Temporal(TemporalType.TIMESTAMP)
	private Date fchIns;
	
	@Column(name = "fch_upd", nullable = true)
	@Temporal(TemporalType.TIMESTAMP)
	private Date fchUpd;
	
	@Column(name = "usuario_ins", nullable = false)
	private String usuarioIns;
	
	@Column(name = "usuario_upd", nullable = true)
	private String usuarioUpd;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@Cascade(value = { CascadeType.LOCK })
	@JoinColumn(name = "id_evento", referencedColumnName = "id_evento")
	private UcsawsEvento idEvento;
	

	public UcsawsLocal() {
	}

	public UcsawsLocal(int idLocal, UcsawsEvento idEvento) {
		this.idLocal = idLocal;
		this.idEvento = idEvento;
	}

	public UcsawsLocal(int idLocal, UcsawsZona ucsawsZona, String descLocal,
			String nroLocal, String usuarioIns, String usuarioUpd, Date fchIns,
			Date fchUpd, UcsawsEvento idEvento) {
		this.idLocal = idLocal;
		this.ucsawsZona = ucsawsZona;
		this.descLocal = descLocal;
		this.nroLocal = nroLocal;
		this.usuarioIns = usuarioIns;
		this.usuarioUpd = usuarioUpd;
		this.fchIns = fchIns;
		this.fchUpd = fchUpd;
		this.idEvento = idEvento;
		
	}

	public int getIdLocal() {
		return this.idLocal;
	}

	public void setIdLocal(int idLocal) {
		this.idLocal = idLocal;
	}

	public UcsawsZona getUcsawsZona() {
		return this.ucsawsZona;
	}

	public void setUcsawsZona(UcsawsZona ucsawsZona) {
		this.ucsawsZona = ucsawsZona;
	}

	public String getDescLocal() {
		return this.descLocal;
	}

	public void setDescLocal(String descLocal) {
		this.descLocal = descLocal;
	}

	public String getNroLocal() {
		return this.nroLocal;
	}

	public void setNroLocal(String nroLocal) {
		this.nroLocal = nroLocal;
	}

	public String getUsuarioIns() {
		return this.usuarioIns;
	}

	public void setUsuarioIns(String usuarioIns) {
		this.usuarioIns = usuarioIns;
	}

	public String getUsuarioUpd() {
		return this.usuarioUpd;
	}

	public void setUsuarioUpd(String usuarioUpd) {
		this.usuarioUpd = usuarioUpd;
	}

	public Date getFchIns() {
		return this.fchIns;
	}

	public void setFchIns(Date fchIns) {
		this.fchIns = fchIns;
	}

	public Date getFchUpd() {
		return this.fchUpd;
	}

	public void setFchUpd(Date fchUpd) {
		this.fchUpd = fchUpd;
	}

	public UcsawsEvento getIdEvento() {
		return this.idEvento;
	}

	public void setIdEvento(UcsawsEvento idEvento) {
		this.idEvento = idEvento;
	}

	

}
