package py.edu.ucsa.voto.entity;
// default package
// Generated 25/04/2017 09:24:26 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

/**
 * UcsawsMesa generated by hbm2java
 */
@Entity
@Table(name = "ucsaws_mesa")
public class UcsawsMesa implements java.io.Serializable {

	@Id
	@Column(name = "id_mesa", nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@SequenceGenerator(name = "generator", sequenceName = "ucsaws_mesa_seq", allocationSize = 1)
	private Integer idMesa;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@Cascade(value = { CascadeType.LOCK })
	@JoinColumn(name = "id_local", referencedColumnName = "id_local")
	private UcsawsLocal ucsawsLocal;
	
	@Column(name = "desc_mesa", nullable = false, length=1000)
	private String descMesa;
	
	@Column(name = "nro_mesa", nullable = false, length=1000)
	private Integer nroMesa;
	
	
	@Column(name = "fch_ins", nullable = false)
	@Temporal(TemporalType.TIMESTAMP)
	private Date fchIns;
	
	@Column(name = "fch_upd", nullable = true)
	@Temporal(TemporalType.TIMESTAMP)
	private Date fchUpd;
	
	@Column(name = "usuario_ins", nullable = false)
	private String usuarioIns;
	
	@Column(name = "usuario_upd", nullable = true)
	private String usuarioUpd;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@Cascade(value = { CascadeType.LOCK })
	@JoinColumn(name = "id_evento", referencedColumnName = "id_evento")
	private UcsawsEvento idEvento;
	

	public UcsawsMesa() {
	}

	public UcsawsMesa(Integer idMesa) {
		this.idMesa = idMesa;
	}

	public UcsawsMesa(Integer idMesa, UcsawsLocal ucsawsLocal, String descMesa,
			String usuarioIns, String usuarioUpd, Date fchIns, Date fchUpd,
			Integer nroMesa, UcsawsEvento idEvento) {
		this.idMesa = idMesa;
		this.ucsawsLocal = ucsawsLocal;
		this.descMesa = descMesa;
		this.usuarioIns = usuarioIns;
		this.usuarioUpd = usuarioUpd;
		this.fchIns = fchIns;
		this.fchUpd = fchUpd;
		this.nroMesa = nroMesa;
		this.idEvento = idEvento;
		
	}

	public Integer getIdMesa() {
		return this.idMesa;
	}

	public void setIdMesa(Integer idMesa) {
		this.idMesa = idMesa;
	}

	public UcsawsLocal getUcsawsLocal() {
		return this.ucsawsLocal;
	}

	public void setUcsawsLocal(UcsawsLocal ucsawsLocal) {
		this.ucsawsLocal = ucsawsLocal;
	}

	public String getDescMesa() {
		return this.descMesa;
	}

	public void setDescMesa(String descMesa) {
		this.descMesa = descMesa;
	}

	public String getUsuarioIns() {
		return this.usuarioIns;
	}

	public void setUsuarioIns(String usuarioIns) {
		this.usuarioIns = usuarioIns;
	}

	public String getUsuarioUpd() {
		return this.usuarioUpd;
	}

	public void setUsuarioUpd(String usuarioUpd) {
		this.usuarioUpd = usuarioUpd;
	}

	public Date getFchIns() {
		return this.fchIns;
	}

	public void setFchIns(Date fchIns) {
		this.fchIns = fchIns;
	}

	public Date getFchUpd() {
		return this.fchUpd;
	}

	public void setFchUpd(Date fchUpd) {
		this.fchUpd = fchUpd;
	}

	public Integer getNroMesa() {
		return this.nroMesa;
	}

	public void setNroMesa(Integer nroMesa) {
		this.nroMesa = nroMesa;
	}

	public UcsawsEvento getIdEvento() {
		return this.idEvento;
	}

	public void setIdEvento(UcsawsEvento idEvento) {
		this.idEvento = idEvento;
	}


}
