package py.edu.ucsa.voto.entity;
// Generated 27/04/2017 04:02:20 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

/**
 * UcsawsVotos generated by hbm2java
 */
@Entity
@Table(name = "ucsaws_votos")
public class UcsawsVotos implements java.io.Serializable {

	@Id
	@Column(name = "id_voto", nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@SequenceGenerator(name = "generator", sequenceName = "ucsaws_votos_seq", allocationSize = 1)
	private Integer idVoto;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@Cascade(value = { CascadeType.LOCK })
	@JoinColumn(name = "id_lista", referencedColumnName = "id_lista")
	private UcsawsListas idLista;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@Cascade(value = { CascadeType.LOCK })
	@JoinColumn(name = "id_mesa", referencedColumnName = "id_mesa")
	private UcsawsMesa idMesa;
	
	
	@Column(name = "fch_ins", nullable = false)
	@Temporal(TemporalType.TIMESTAMP)
	private Date fchIns;
	
	@Column(name = "fch_upd", nullable = true)
	@Temporal(TemporalType.TIMESTAMP)
	private Date fchUpd;
	
	@Column(name = "usuario_ins", nullable = false)
	private String usuarioIns;
	
	@Column(name = "usuario_upd", nullable = true)
	private String usuarioUpd;

	public UcsawsVotos() {
	}

	public UcsawsVotos(Integer idVoto, UcsawsListas idLista, UcsawsMesa idMesa, Date fchIns,
			String usuarioIns) {
		this.idVoto = idVoto;
		this.idLista = idLista;
		this.idMesa = idMesa;
		this.fchIns = fchIns;
		this.usuarioIns = usuarioIns;
	}

	public UcsawsVotos(Integer idVoto, UcsawsListas idLista, UcsawsMesa idMesa, Date fchIns,
			Date fchUpd, String usuarioIns, String usuarioUpd) {
		this.idVoto = idVoto;
		this.idLista = idLista;
		this.idMesa = idMesa;
		this.fchIns = fchIns;
		this.fchUpd = fchUpd;
		this.usuarioIns = usuarioIns;
		this.usuarioUpd = usuarioUpd;
	}

	public Integer getIdVoto() {
		return this.idVoto;
	}

	public void setIdVoto(Integer idVoto) {
		this.idVoto = idVoto;
	}

	public UcsawsListas getIdLista() {
		return this.idLista;
	}

	public void setIdLista(UcsawsListas idLista) {
		this.idLista = idLista;
	}

	public UcsawsMesa getIdMesa() {
		return this.idMesa;
	}

	public void setIdMesa(UcsawsMesa idMesa) {
		this.idMesa = idMesa;
	}

	public Date getFchIns() {
		return this.fchIns;
	}

	public void setFchIns(Date fchIns) {
		this.fchIns = fchIns;
	}

	public Date getFchUpd() {
		return this.fchUpd;
	}

	public void setFchUpd(Date fchUpd) {
		this.fchUpd = fchUpd;
	}

	public String getUsuarioIns() {
		return this.usuarioIns;
	}

	public void setUsuarioIns(String usuarioIns) {
		this.usuarioIns = usuarioIns;
	}

	public String getUsuarioUpd() {
		return this.usuarioUpd;
	}

	public void setUsuarioUpd(String usuarioUpd) {
		this.usuarioUpd = usuarioUpd;
	}

}
