package py.edu.ucsa.voto.entity;

// Generated 22/04/2017 08:46:05 PM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

/**
 * UcsawsRoles generated by hbm2java
 */

@Entity
@Table(name = "ucsaws_roles")
public class UcsawsRoles //extends AbstractFechaUsuario 
implements Serializable {

	public UcsawsRoles(Integer idRol, UcsawsEvento ucsawsEvento, String codigo,
			String descripcion, Date fchIns, Date fchUpd, String usuarioIns,
			String usuarioUpd) {
		//super();
		this.idRol = idRol;
		this.ucsawsEvento = ucsawsEvento;
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.fchins = fchIns;
		this.fchupd = fchUpd;
		this.usuarioIns = usuarioIns;
		this.usuarioUpd = usuarioUpd;
	}
 
	@Id
	@Column(name = "id_rol", nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
	@SequenceGenerator(name = "generator", sequenceName = "ucsaws_roles_seq", allocationSize = 1)
	private Integer idRol;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@Cascade(value = { CascadeType.LOCK })
	@JoinColumn(name = "id_Evento", referencedColumnName = "id_Evento")
	private UcsawsEvento ucsawsEvento;
	
	@Column(name = "codigo", nullable = false)
	private String codigo;
	
	@Column(name = "descripcion", nullable = false, length=1000)
	private String descripcion;
	
	
	@Column(name = "fch_ins", nullable = false)
	@Temporal(TemporalType.TIMESTAMP)
	private Date fchins;
	
	@Column(name = "fch_upd", nullable = true)
	@Temporal(TemporalType.TIMESTAMP)
	private Date fchupd;
	
	@Column(name = "usuario_ins", nullable = true)
	private String usuarioIns;
	
	@Column(name = "usuario_upd", nullable = true)
	private String usuarioUpd;

	public UcsawsRoles() {
	}

	public Integer getIdRol() {
		return idRol;
	}

	public void setIdRol(Integer idRol) {
		this.idRol = idRol;
	}

	public UcsawsEvento getUcsawsEvento() {
		return ucsawsEvento;
	}

	public void setUcsawsEvento(UcsawsEvento ucsawsEvento) {
		this.ucsawsEvento = ucsawsEvento;
	}

	public String getCodigo() {
		return codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Date getFchIns() {
		return fchins;
	}

	public void setFchIns(Date fchIns) {
		this.fchins = fchIns;
	}

	public Date getFchUpd() {
		return fchupd;
	}

	public void setFchUpd(Date fchUpd) {
		this.fchupd = fchUpd;
	}

	public String getUsuarioIns() {
		return usuarioIns;
	}

	public void setUsuarioIns(String usuarioIns) {
		this.usuarioIns = usuarioIns;
	}

	public String getUsuarioUpd() {
		return usuarioUpd;
	}

	public void setUsuarioUpd(String usuarioUpd) {
		this.usuarioUpd = usuarioUpd;
	}

	
}
